name: Phonkstax Media Pipeline

on:
  workflow_dispatch: # Manual trigger for testing

# Grant write permissions for committing assets back to the repo
permissions:
  contents: write

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

     
      - name: Step 1 - Notion & Playlist Check
        env:
          YTM_CLIENT_ID: ${{ secrets.YTM_CLIENT_ID }}
          YTM_CLIENT_SECRET: ${{ secrets.YTM_CLIENT_SECRET }}
          YTM_OAUTH_JSON: ${{ secrets.YTM_OAUTH_JSON }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: python check_and_process_old.py
        
      

      - name: Step 4 - Commit Assets to Repo
        run: |
          if [ -f metadata.json ]; then
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.email "bot@phonkstax.com"
            git add assets/ metadata.json
            
            # Use jq to get the title for the commit message if available
            TITLE=$(cat metadata.json | jq -r '.title' || echo "New Reel")
            
            git commit -m "📦 Assets Extracted: $TITLE"
            git push
          else
            echo "✅ Nothing to commit."
          fi
